#!/bin/bash
# load the singularity module on the cluster
module load singularity/3.10.2

# paths file that was generated by mkpths.sh
export SUB_PATHS_FILE=/data/users2/mjafarlou1/code/megprep_docker/paths
SLURM_ARRAY_TASK_ID=0


# parse paths file into array and collect arguments for current subject
export IFS=$'\n'
export paths_array=($(cat ${SUB_PATHS_FILE}))

export fif_ix=$(( 4*$SLURM_ARRAY_TASK_ID ))
export fs_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 1 ))
export out_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 2 ))
export sub_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 3 ))


# collect script arguments from paths file array
export fif_filepath=${paths_array[${fif_ix}]} # first argument of MEG_preprocessing.py script
echo "fif_filepath : $fif_filepath"

export FREESURFER_DIR=${paths_array[${fs_ix}]} # second argument of MEG_preprocessing.py script
echo "FREESURFER_DIR : $FREESURFER_DIR"

export OUTPUT_DIR=${paths_array[${out_ix}]} # third argument of MEG_preprocessing.py script
echo "OUTPUT_DIR : $OUTPUT_DIR"

export SUBJECT_ID=${paths_array[${sub_ix}]} # fourth argument of MEG_preprocessing.py script
echo "SUBJECT_ID : $SUBJECT_ID"

# for binding directory to singularity container
export FIF_DIR=`dirname ${fif_filepath}`

# to attach to /fif bind name in singularity container
export FIF_FILENAME=`basename ${fif_filepath}`

# where the script is located to be excuted in the singularity container
#RUN_BIND_POINT=/data/users2/mjafarlou1/code

# name of the singularity .sif file
export SIF_FILE=/data/users2/mjafarlou1/code/megprep_docker/megprep.sif

# name of script to be executed inside singularity container
export SCRIPT_NAME=MEG_preprocessing.py

